apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdb-convert
  namespace: prod
spec:
  replicas: 15
  selector:
    matchLabels:
      app: cmdb-convert
  template:
    metadata:
      labels:
        app: cmdb-convert
    spec:
      serviceAccountName: cmdb-convert-sa
      containers:
      - name: cmdb-convert
        # 초기 이미지 버전 세팅
        image: 061051247564.dkr.ecr.ap-northeast-2.amazonaws.com/cmdb-convert:0.25.4
        env:
        - name: app/create-datetime
          value: "20251004083056"
        ports:
        - containerPort: 8080
