apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdb-convert
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmdb-convert
  template:
    metadata:
      labels:
        app: cmdb-convert
    spec:
      containers:
      - name: cmdb-convert
        image: nginx:latest
        ports:
        - containerPort: 80
